const defaultConfig = require('@wordpress/scripts/config/webpack.config'),
	  NoEmitPlugin = require('no-emit-webpack-plugin');

const { resolve } = require('path');

defaultConfig.plugins.map( p => {
    if(p.constructor.name == 'CleanWebpackPlugin') {
		//Do not delete the file generated by rtlcss during build
		p.cleanOnceBeforeBuildPatterns.push('!*-rtl.css');
    }
	return p;
});

module.exports = {
	...defaultConfig,
	stats: {
		modules: false
	},
	context: resolve(__dirname, '../assets/scss'),
	entry: {
		editor: './editor.scss',
		style: './style.scss',
	},
	optimization: {
		...defaultConfig.optimization,
		splitChunks: false,
	},
	plugins: [
		...defaultConfig.plugins,
		new NoEmitPlugin([
			'editor.js', 
			'style.js'
		]),
	],
};
